registry_linuxwt:

    restart: always

    image: registry:latest

    container_name: registry_linuxwt

    volumes:
       
        - ./auth:/auth       
 
        - ./registry:/var/lib/registry

        - ./registry.linuxwt.com.crt:/cert/registry.linuxwt.com.crt

        - ./registry.linuxwt.com.key:/cert/registry.linuxwt.com.key

        - /etc/localtime:/etc/localtime

        - /etc/timezone:/etc/timezone

        - ./config.yml:/etc/docker/registry/config.yml

    privileged: true
   
    environment:
  
         REGISTRY_AUTH: "htpasswd"

         REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"

         REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"

         REGISTRY_HTTP_TLS_CERTIFICATE: "/cert/registry.linuxwt.com.crt"
  
         REGISTRY_HTTP_TLS_KEY: "/cert/registry.linuxwt.com.key"

    ports:

       - "5000:5000"



nginx_linuxwt:

     restart: always

     image: nginx:1.15

     container_name: nginx_linuxwt

     volumes:
   
        - ./registry.linuxwt.com.crt:/etc/registry.linuxwt.com.crt

        - ./registry.linuxwt.com.key:/etc/registry.linuxwt.com.key

        - ./nginx.conf:/etc/nginx/nginx.conf

        - ./nginx_flask.conf:/etc/nginx/conf.d/default.conf

        - /etc/localtime:/etc/localtime

        - /etc/timezone:/etc/timezone

     privileged: true

     links:

        - registry_linuxwt
 
     ports:

        - "80:80"
 
        - "443:443"

webui:
    restart: always
    image: hyper/docker-registry-web
    container_name: registry_webui
    privileged: true
    volumes:
       - ./web-config.yml:/conf/config.yml
       - ./db:/data
    environment:
       REGISTRY_URL: "https://registry.linuxwt.com/v2"
       REGISTRY_TRUST_ANY_SSL: "true"
       REGISTRY_NAME: "registry.linuxwt.com"
       REGISTRY_BASIC_AUTH: "d2FuZ3Rlbmc6MTIzNDU2"
    ports:
      - "8080:8080"
