registry:
  # Docker registry url
  url: https://registry.linuxwt.com/v2
  # Docker registry fqdn
  name: registry.linuxwt.com:5000
  # To allow image delete, should be false
  readonly: false
  auth:
    # Disable authentication
    enabled: false
